version: "2"

services:

  livechat:
    #build: .
    image: ${REGISTRY_URL}/autodesk-forge-viewmodels
    ports: 
    - "${HTTP_PORT}:3000"
    environment: 
    - FORGE_CLIENT_ID
    - FORGE_CLIENT_SECRET
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"