version: "3"

services:

  bimviewer:
    image: ${REGISTRY_URL}/autodesk-forge-viewmodels
    networks:
      default:
      hub_net:
        aliases: 
        - ${HUB_INSTANCE}
    environment: 
    - FORGE_CLIENT_ID
    - FORGE_CLIENT_SECRET
    - SERVER_WEBROOT
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"

networks: 
  hub_net:
    external: true