version: "2"

services:

  livechat:
    #build: .
    image: registry.sangah.com/autodesk-forge-viewmodels
    ports: 
    - "${HTTP_PORT}:3000"
    environment: 
    - SERVER_WEBROOT
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"